import generateUniqueId from "generate-unique-id";

export const galleryImages = [
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery0.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery40.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery44.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery43.jpeg",
    height: 1080,
    width: 768,
  },

  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery45.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery41.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery46.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery47.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery42.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery48.jpeg",
    height: 1080,
    width: 768,
  },

  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery1.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery2.jpeg",
    height: 1080,
    width: 768,
  },

  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery3.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery4.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery4.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery6.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery7.jpeg",
    height: 1080,
    width: 768,
  },

  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery8.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery9.jpeg",
    height: 1080,
    width: 768,
  },

  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery10.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery11.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery12.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery13.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery14.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery15.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery16.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery17.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery18.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery19.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery20.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery21.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery22.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery23.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery24.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery25.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery26.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery27.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery28.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery29.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery30.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery32.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery33.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery34.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery35.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery36.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery37.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery38.jpeg",
    height: 1080,
    width: 768,
  },
  {
    id: generateUniqueId(),
    url: "/galleryImages/gallery39.jpeg",
    height: 1080,
    width: 768,
  },
];
